server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=0

        - id: movie-service-route
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/movies/**,/api/actors/**,/api/directors/**,/api/genres/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@keyResolver}"
                deny-empty-key: false

        - id: cinema-service-route
          uri: lb://CINEMA-SERVICE
          predicates:
            - Path=/api/cinemas/**,/api/halls/**,/api/seats/**,/api/seat-types/**,/api/hall-maintenances/**
          filters:
            - StripPrefix=0

        - id: showtime-service-route
          uri: lb://SHOWTIME-SERVICE
          predicates:
            - Path=/api/showtimes/**
          filters:
            - StripPrefix=0

        - id: booking-service-route
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**,/api/admin/booking-settings/**
          filters:
            - StripPrefix=0

        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/**,/ping
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "*"
            allow-credentials: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5

app:
  jwt:
    secret: myMovieTicketSecretKey12345678901234567890
management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
