spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 10000
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 45s

management:
  endpoints:
    web:
      exposure:
        include: health, info, env