server:
  port: 8081


spring:
  application:
    name: USER-SERVICE


  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



# =====================
# JWT CONFIG
# =====================
jwt:
  secret: movie-ticket-secret-key-2026-super-secret
  expiration: 86400000



# =====================
# SWAGGER
# =====================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  api-docs:
    path: /v3/api-docs



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
