server:
  port: 8083

spring:
  application:
    name: cinema-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: simple

  data:
    redis:
      repositories:
        enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always