import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BellRing, Mail, Plus, Send } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { notificationApi } from '../../api/notificationApi'
import { EmptyState, ErrorState, SkeletonGrid } from '../../components/common/AsyncState'
import { StatusBadge } from '../../components/common/StatusBadge'
import { getApiError } from '../../utils/apiError'
import { displayValue, formatDateTime } from '../../utils/formatters'

const types = ['BOOKING_CONFIRMATION', 'BOOKING_CANCELLED', 'SEAT_HOLD_CREATED', 'SEAT_HOLD_EXPIRED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SHOWTIME_REMINDER', 'TICKET_CANCELLED', 'SYSTEM_ALERT']

function Heading({ title, description }) { return <div className="admin-page-title"><div><span className="eyebrow"><BellRing /> Notification service</span><h1>{title}</h1><p>{description}</p></div></div> }

export function AdminNotificationsPage() {
  const [form, setForm] = useState({ recipientEmail: '', subject: '', message: '', channel: 'EMAIL', type: 'SYSTEM_ALERT' })
  const [lastResult, setLastResult] = useState(null)
  const ping = useQuery({ queryKey: ['notification', 'ping'], queryFn: notificationApi.ping, retry: false })
  const send = useMutation({ mutationFn: notificationApi.send, onSuccess: (data) => { setLastResult(data); toast.success(data.status === 'SENT' ? 'Thông báo đã gửi' : `Backend trả trạng thái ${data.status}`) }, onError: (error) => toast.error(getApiError(error)) })
  return <div><Heading title="Gửi thông báo" description="Gửi qua API hiện có và hiển thị đúng trạng thái backend trả về. EMAIL là kênh được triển khai đầy đủ trong mã nguồn hiện tại." /><div className="service-status"><span className={ping.isSuccess ? 'online' : 'offline'} /> Notification service: {ping.isLoading ? 'đang kiểm tra' : ping.isSuccess ? 'kết nối được' : 'không phản hồi'}</div><div className="admin-split"><form className="panel admin-form" onSubmit={(e) => { e.preventDefault(); send.mutate(form) }}><label>Email người nhận<input required type="email" value={form.recipientEmail} onChange={(e) => setForm({ ...form, recipientEmail: e.target.value })} /></label><label>Tiêu đề<input required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label>Nội dung<textarea required rows="7" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></label><label>Kênh<select value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value })}><option value="EMAIL">EMAIL — đang hỗ trợ</option><option value="SMS">SMS — backend sẽ trả trạng thái thực tế</option></select></label><label>Loại thông báo<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{types.map((item) => <option key={item}>{item}</option>)}</select></label><p className="info-note">Mã nguồn service hiện chỉ thực hiện gửi EMAIL; SMS có thể được ghi nhận với trạng thái thất bại.</p><button className="button button-primary full" disabled={send.isPending}><Send /> {send.isPending ? 'Đang gửi...' : 'Gửi thông báo'}</button></form><section className="panel"><h2>Kết quả gần nhất</h2>{lastResult ? <div className="notification-result"><StatusBadge value={lastResult.status} /><dl><div><dt>Người nhận</dt><dd>{lastResult.recipientEmail}</dd></div><div><dt>Kênh</dt><dd>{lastResult.channel}</dd></div><div><dt>Loại</dt><dd>{lastResult.type}</dd></div><div><dt>Thời gian</dt><dd>{formatDateTime(lastResult.createdAt)}</dd></div><div><dt>Lỗi backend</dt><dd>{displayValue(lastResult.errorMessage, 'Không có')}</dd></div></dl></div> : <EmptyState title="Chưa gửi thông báo" message="Kết quả từ API sẽ hiển thị tại đây." />}</section></div></div>
}

export function AdminNotificationTemplatesPage() {
  const queryClient = useQueryClient(); const [form, setForm] = useState({ code: '', subject: '', body: '' })
  const query = useQuery({ queryKey: ['admin', 'notification-templates'], queryFn: notificationApi.templates })
  const create = useMutation({ mutationFn: notificationApi.createTemplate, onSuccess: () => { toast.success('Đã tạo mẫu thông báo'); queryClient.invalidateQueries({ queryKey: ['admin', 'notification-templates'] }); setForm({ code: '', subject: '', body: '' }) }, onError: (error) => toast.error(getApiError(error)) })
  return <div><Heading title="Mẫu thông báo" description="Backend chỉ hỗ trợ tạo và xem danh sách mẫu; không có chức năng sửa hoặc xóa." /><div className="admin-split"><form className="panel admin-form" onSubmit={(e) => { e.preventDefault(); create.mutate(form) }}><label>Mã mẫu<input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label><label>Tiêu đề<input required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label>Nội dung mẫu<textarea required rows="8" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /></label><button className="button button-primary full" disabled={create.isPending}><Plus /> Tạo mẫu</button></form><section className="template-list">{query.isLoading ? <SkeletonGrid count={4} compact /> : query.isError ? <ErrorState message={getApiError(query.error)} /> : !(query.data || []).length ? <EmptyState title="Chưa có mẫu" /> : query.data.map((item) => <article className="panel template-card" key={item.id}><Mail /><div><span className="eyebrow">{item.code}</span><h2>{item.subject}</h2><p>{item.body}</p></div></article>)}</section></div></div>
}

export function AdminNotificationLogsPage() {
  const query = useQuery({ queryKey: ['admin', 'notification-logs'], queryFn: notificationApi.logs, refetchInterval: 30000 })
  return <div><Heading title="Nhật ký thông báo" description="Danh sách trạng thái gửi do API trả về; tự làm mới mỗi 30 giây." />{query.isLoading ? <SkeletonGrid count={6} compact /> : query.isError ? <ErrorState message={getApiError(query.error)} onRetry={query.refetch} /> : !(query.data || []).length ? <EmptyState title="Chưa có nhật ký" /> : <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Người nhận</th><th>Thông báo</th><th>Kênh / Loại</th><th>Trạng thái</th><th>Thử lại</th><th>Thời gian</th></tr></thead><tbody>{query.data.map((item) => <tr key={item.id}><td>{item.recipientEmail}</td><td><strong>{item.subject}</strong><small className="cell-clamp">{item.message}</small>{item.errorMessage && <small className="field-error">{item.errorMessage}</small>}</td><td>{item.channel}<small>{item.type}</small></td><td><StatusBadge value={item.status} /></td><td>{item.retryCount}/{item.maxRetries}</td><td>{formatDateTime(item.sentAt || item.createdAt)}</td></tr>)}</tbody></table></div></section>}</div>
}
