\set ON_ERROR_STOP on

-- ============================================================
-- MOVIE TICKET BOOKING SYSTEM
-- POSTGRESQL DATABASE INITIALIZATION
--
-- Chức năng:
-- 1. Tạo các database cho toàn bộ microservice
-- 2. Tạo bảng và dữ liệu mẫu cho Movie Service
-- 3. Tạo bảng và dữ liệu mẫu cho Cinema Service
-- 4. Tạo bảng và dữ liệu mẫu cho Booking Service
-- 5. Tạo bảng và dữ liệu mẫu cho Notification Service
--
-- File chỉ tự chạy khi PostgreSQL Docker Volume còn trống.
-- ============================================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;


-- ============================================================
-- PHẦN 1: TẠO DATABASE
-- ============================================================

SELECT 'CREATE DATABASE user_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'user_db'
)
    \gexec

SELECT 'CREATE DATABASE movie_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'movie_db'
)
    \gexec

SELECT 'CREATE DATABASE cinema_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'cinema_db'
)
    \gexec

SELECT 'CREATE DATABASE showtime_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'showtime_db'
)
    \gexec

SELECT 'CREATE DATABASE booking_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'booking_db'
)
    \gexec

SELECT 'CREATE DATABASE notification_db'
    WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'notification_db'
)
    \gexec


-- ============================================================
-- PHẦN 2: MOVIE DATABASE
-- ============================================================

-- ============================================================
-- USER DATABASE
-- The User Service creates seed accounts itself at startup. This section
-- intentionally creates schema only, so a fresh database is immediately
-- queryable before that service is restarted.
-- ============================================================

    \connect user_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;

CREATE TABLE public.users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    full_name     VARCHAR(255),
    phone         VARCHAR(255),
    avatar        VARCHAR(255),
    date_of_birth DATE,
    gender        VARCHAR(255),
    is_active     BOOLEAN,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE public.roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE public.user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles (id)
);

CREATE TABLE public.refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(500) NOT NULL UNIQUE,
    user_id     BIGINT NOT NULL,
    expiry_date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    revoked     BOOLEAN,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX idx_users_email ON public.users (email);
CREATE INDEX idx_users_username ON public.users (username);
CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens (user_id);


\connect movie_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;


-- ============================================================
-- 2.1. TẠO BẢNG ACTORS
-- ============================================================

CREATE TABLE public.actors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    avatar_url VARCHAR(500),
    biography  TEXT,
    birth_date DATE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name       VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT actors_pkey
        PRIMARY KEY (id)
);


-- ============================================================
-- 2.2. TẠO BẢNG DIRECTORS
-- ============================================================

CREATE TABLE public.directors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    biography  TEXT,
    birth_date DATE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name       VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT directors_pkey
        PRIMARY KEY (id)
);


-- ============================================================
-- 2.3. TẠO BẢNG GENRES
-- ============================================================

CREATE TABLE public.genres
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    description TEXT,
    name        VARCHAR(100) NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT genres_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_genres_name
        UNIQUE (name)
);


-- ============================================================
-- 2.4. TẠO BẢNG MOVIES
-- ============================================================

CREATE TABLE public.movies
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    age_rating       VARCHAR(20) NOT NULL,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    description      TEXT,
    duration_minutes INTEGER NOT NULL,
    poster_url       VARCHAR(500),
    release_date     DATE NOT NULL,
    status           VARCHAR(30) NOT NULL,
    title            VARCHAR(255) NOT NULL,
    trailer_url      VARCHAR(500) NOT NULL,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT movies_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_movie_title_release_date
        UNIQUE (title, release_date),

    CONSTRAINT movies_age_rating_check
        CHECK (
            age_rating IN (
                           'P',
                           'C13',
                           'C16',
                           'C18'
                )
            ),

    CONSTRAINT movies_status_check
        CHECK (
            status IN (
                       'COMING_SOON',
                       'NOW_SHOWING',
                       'ENDED'
                )
            ),

    CONSTRAINT movies_duration_check
        CHECK (duration_minutes > 0)
);


-- ============================================================
-- 2.5. TẠO BẢNG MOVIE_ACTORS
-- ============================================================

CREATE TABLE public.movie_actors
(
    actor_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    role_name VARCHAR(255) NOT NULL,

    CONSTRAINT movie_actors_pkey
        PRIMARY KEY (actor_id, movie_id),

    CONSTRAINT fk_movie_actors_actor
        FOREIGN KEY (actor_id)
            REFERENCES public.actors (id),

    CONSTRAINT fk_movie_actors_movie
        FOREIGN KEY (movie_id)
            REFERENCES public.movies (id)
);


-- ============================================================
-- 2.6. TẠO BẢNG MOVIE_DIRECTORS
-- ============================================================

CREATE TABLE public.movie_directors
(
    director_id BIGINT NOT NULL,
    movie_id    BIGINT NOT NULL,

    CONSTRAINT movie_directors_pkey
        PRIMARY KEY (director_id, movie_id),

    CONSTRAINT fk_movie_directors_director
        FOREIGN KEY (director_id)
            REFERENCES public.directors (id),

    CONSTRAINT fk_movie_directors_movie
        FOREIGN KEY (movie_id)
            REFERENCES public.movies (id)
);


-- ============================================================
-- 2.7. TẠO BẢNG MOVIE_GENRES
-- ============================================================

CREATE TABLE public.movie_genres
(
    genre_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,

    CONSTRAINT movie_genres_pkey
        PRIMARY KEY (genre_id, movie_id),

    CONSTRAINT fk_movie_genres_genre
        FOREIGN KEY (genre_id)
            REFERENCES public.genres (id),

    CONSTRAINT fk_movie_genres_movie
        FOREIGN KEY (movie_id)
            REFERENCES public.movies (id)
);


-- ============================================================
-- 2.8. INDEX MOVIE
-- ============================================================

CREATE INDEX idx_movies_status
    ON public.movies (status);

CREATE INDEX idx_movies_release_date
    ON public.movies (release_date);

CREATE INDEX idx_movies_title
    ON public.movies (title);


-- ============================================================
-- 2.9. DỮ LIỆU GENRES
-- ============================================================

INSERT INTO public.genres
(
    id,
    name,
    description,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'Science Fiction',
        'Phim khoa học viễn tưởng, không gian và công nghệ tương lai.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Adventure',
        'Phim phiêu lưu, khám phá và hành trình vượt thử thách.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'Drama',
        'Phim chính kịch, tâm lý và các mối quan hệ xã hội.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        'Action',
        'Phim hành động có nhịp độ nhanh và nhiều cảnh đối đầu.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        'Animation',
        'Phim hoạt hình dành cho khán giả gia đình.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        'Thriller',
        'Phim giật gân, điều tra và bí ẩn.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 2.10. DỮ LIỆU ACTORS
-- ============================================================

INSERT INTO public.actors
(
    id,
    name,
    avatar_url,
    biography,
    birth_date,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'Linh Tran',
        'https://example.com/actors/linh-tran.jpg',
        'Diễn viên chuyên các vai hành động và khoa học viễn tưởng.',
        DATE '1992-04-18',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Nam Le',
        'https://example.com/actors/nam-le.jpg',
        'Diễn viên điện ảnh với thế mạnh ở dòng phim phiêu lưu.',
        DATE '1988-09-07',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'Mai Pham',
        'https://example.com/actors/mai-pham.jpg',
        'Diễn viên chính kịch và phim tâm lý.',
        DATE '1995-12-21',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        'Khoa Nguyen',
        'https://example.com/actors/khoa-nguyen.jpg',
        'Diễn viên trẻ được biết đến qua các vai kỹ sư và nhà khoa học.',
        DATE '1997-06-11',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        'Vy Hoang',
        'https://example.com/actors/vy-hoang.jpg',
        'Diễn viên lồng tiếng và điện ảnh gia đình.',
        DATE '1994-02-28',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        'An Do',
        'https://example.com/actors/an-do.jpg',
        'Diễn viên hành động với kinh nghiệm biểu diễn võ thuật.',
        DATE '1985-10-03',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        'My Bui',
        'https://example.com/actors/my-bui.jpg',
        'Diễn viên chuyên các vai phóng viên và điều tra viên.',
        DATE '1991-08-16',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        'Huy Phan',
        'https://example.com/actors/huy-phan.jpg',
        'Diễn viên phản diện trong các phim trinh thám và giật gân.',
        DATE '1983-01-25',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 2.11. DỮ LIỆU DIRECTORS
-- ============================================================

INSERT INTO public.directors
(
    id,
    name,
    biography,
    birth_date,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'Minh Nguyen',
        'Đạo diễn phim khoa học viễn tưởng và hành động.',
        DATE '1978-03-15',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Ha Do',
        'Đạo diễn dòng phim chính kịch và tâm lý.',
        DATE '1982-11-02',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'Quang Vu',
        'Đạo diễn phim hoạt hình và nội dung gia đình.',
        DATE '1980-07-09',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        'Lan Truong',
        'Đạo diễn phim trinh thám và giật gân.',
        DATE '1976-05-20',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 2.12. DỮ LIỆU MOVIES
-- ============================================================

INSERT INTO public.movies
(
    id,
    title,
    description,
    duration_minutes,
    trailer_url,
    poster_url,
    release_date,
    age_rating,
    status,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'Stellar Horizon',
        'Một đội phi hành gia tìm kiếm nguồn năng lượng mới ở rìa thiên hà.',
        142,
        'https://www.youtube.com/watch?v=stellar-horizon',
        'https://example.com/posters/stellar-horizon.jpg',
        DATE '2026-06-20',
        'C13',
        'NOW_SHOWING',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Saigon Midnight',
        'Một cảnh sát hình sự lần theo đường dây tội phạm hoạt động trong đêm.',
        126,
        'https://www.youtube.com/watch?v=saigon-midnight',
        'https://example.com/posters/saigon-midnight.jpg',
        DATE '2026-07-01',
        'C16',
        'NOW_SHOWING',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'Chronicles of Tomorrow',
        'Một nhóm bạn phát hiện cánh cổng dẫn tới tương lai và phải ngăn một thảm họa.',
        128,
        'https://www.youtube.com/watch?v=chronicles-tomorrow',
        'https://example.com/posters/chronicles-tomorrow.jpg',
        DATE '2026-09-10',
        'C13',
        'COMING_SOON',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        'The Last Lantern',
        'Một cô bé cùng chiếc đèn phép thuật bắt đầu hành trình tìm lại ánh sáng cho thành phố.',
        98,
        'https://www.youtube.com/watch?v=the-last-lantern',
        'https://example.com/posters/the-last-lantern.jpg',
        DATE '2026-12-18',
        'P',
        'COMING_SOON',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        'Silent Echoes',
        'Một nhà báo trở về quê nhà để điều tra bí mật bị chôn giấu nhiều năm.',
        116,
        'https://www.youtube.com/watch?v=silent-echoes',
        'https://example.com/posters/silent-echoes.jpg',
        DATE '2026-03-01',
        'C16',
        'ENDED',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        'Crimson Protocol',
        'Một đặc vụ phải ngăn chặn kế hoạch tấn công mạng trước thời hạn cuối cùng.',
        134,
        'https://www.youtube.com/watch?v=crimson-protocol',
        'https://example.com/posters/crimson-protocol.jpg',
        DATE '2026-02-14',
        'C18',
        'ENDED',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 2.13. DỮ LIỆU MOVIE_GENRES
-- ============================================================

INSERT INTO public.movie_genres
(
    movie_id,
    genre_id
)
VALUES
    (1, 1),
    (1, 2),
    (1, 4),

    (2, 3),
    (2, 4),
    (2, 6),

    (3, 1),
    (3, 2),

    (4, 2),
    (4, 5),

    (5, 3),
    (5, 6),

    (6, 4),
    (6, 6);


-- ============================================================
-- 2.14. DỮ LIỆU MOVIE_ACTORS
-- ============================================================

INSERT INTO public.movie_actors
(
    movie_id,
    actor_id,
    role_name
)
VALUES
    (1, 1, 'Captain An'),
    (1, 2, 'Engineer Khoa'),
    (1, 4, 'Scientist Duy'),

    (2, 6, 'Detective Long'),
    (2, 8, 'Mr. Black'),
    (2, 3, 'Reporter Ha'),

    (3, 1, 'Vy'),
    (3, 3, 'Lan'),
    (3, 4, 'Tuan'),

    (4, 5, 'Lumi'),
    (4, 2, 'Guardian'),

    (5, 7, 'Journalist My'),
    (5, 8, 'Mr. Vu'),

    (6, 6, 'Agent Bao'),
    (6, 8, 'Commander K');


-- ============================================================
-- 2.15. DỮ LIỆU MOVIE_DIRECTORS
-- ============================================================

INSERT INTO public.movie_directors
(
    movie_id,
    director_id
)
VALUES
    (1, 1),
    (2, 4),
    (3, 1),
    (4, 3),
    (5, 2),
    (6, 4);


-- ============================================================
-- 2.16. CẬP NHẬT SEQUENCE MOVIE
-- ============================================================

SELECT setval(
               pg_get_serial_sequence('public.genres', 'id'),
               (SELECT MAX(id) FROM public.genres),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.actors', 'id'),
               (SELECT MAX(id) FROM public.actors),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.directors', 'id'),
               (SELECT MAX(id) FROM public.directors),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.movies', 'id'),
               (SELECT MAX(id) FROM public.movies),
               TRUE
       );


-- ============================================================
-- PHẦN 3: CINEMA DATABASE
-- ============================================================

\connect cinema_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;


-- ============================================================
-- 3.1. TẠO BẢNG CINEMAS
-- ============================================================

CREATE TABLE public.cinemas
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address       TEXT,
    city          VARCHAR(100),
    contact_phone VARCHAR(50),
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    latitude      NUMERIC(10,7),
    longitude     NUMERIC(10,7),
    name          VARCHAR(255) NOT NULL,
    status        VARCHAR(30) NOT NULL,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT cinemas_pkey
        PRIMARY KEY (id),

    CONSTRAINT cinemas_status_check
        CHECK (
            status IN (
                       'ACTIVE',
                       'INACTIVE'
                )
            )
);


-- ============================================================
-- 3.2. TẠO BẢNG SEAT_TYPES
-- ============================================================

CREATE TABLE public.seat_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(50) NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    description TEXT,
    name        VARCHAR(100) NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT seat_types_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_seat_types_code
        UNIQUE (code)
);


-- ============================================================
-- 3.3. TẠO BẢNG HALLS
-- ============================================================

CREATE TABLE public.halls
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    capacity   INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    hall_type  VARCHAR(30) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    status     VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    cinema_id  BIGINT NOT NULL,

    CONSTRAINT halls_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_hall_cinema_name
        UNIQUE (cinema_id, name),

    CONSTRAINT halls_hall_type_check
        CHECK (
            hall_type IN (
                          'STANDARD',
                          'VIP',
                          'IMAX',
                          'FOUR_DX'
                )
            ),

    CONSTRAINT halls_status_check
        CHECK (
            status IN (
                       'ACTIVE',
                       'INACTIVE',
                       'MAINTENANCE'
                )
            ),

    CONSTRAINT halls_capacity_check
        CHECK (capacity > 0),

    CONSTRAINT fk_halls_cinema
        FOREIGN KEY (cinema_id)
            REFERENCES public.cinemas (id)
);


-- ============================================================
-- 3.4. TẠO BẢNG SEATS
-- ============================================================

CREATE TABLE public.seats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    row_name     VARCHAR(10) NOT NULL,
    seat_number  INTEGER NOT NULL,
    status       VARCHAR(30) NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    hall_id      BIGINT NOT NULL,
    seat_type_id BIGINT NOT NULL,

    CONSTRAINT seats_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_seat_hall_row_number
        UNIQUE (hall_id, row_name, seat_number),

    CONSTRAINT seats_status_check
        CHECK (
            status IN (
                       'ACTIVE',
                       'BROKEN',
                       'DISABLED'
                )
            ),

    CONSTRAINT seats_number_check
        CHECK (seat_number > 0),

    CONSTRAINT fk_seats_hall
        FOREIGN KEY (hall_id)
            REFERENCES public.halls (id),

    CONSTRAINT fk_seats_seat_type
        FOREIGN KEY (seat_type_id)
            REFERENCES public.seat_types (id)
);


-- ============================================================
-- 3.5. TẠO BẢNG HALL_MAINTENANCE
-- ============================================================

CREATE TABLE public.hall_maintenance
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    end_time   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    reason     TEXT,
    start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status     VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    hall_id    BIGINT NOT NULL,

    CONSTRAINT hall_maintenance_pkey
        PRIMARY KEY (id),

    CONSTRAINT hall_maintenance_status_check
        CHECK (
            status IN (
                       'SCHEDULED',
                       'IN_PROGRESS',
                       'COMPLETED',
                       'CANCELLED'
                )
            ),

    CONSTRAINT hall_maintenance_time_check
        CHECK (end_time > start_time),

    CONSTRAINT fk_hall_maintenance_hall
        FOREIGN KEY (hall_id)
            REFERENCES public.halls (id)
);


-- ============================================================
-- 3.6. DỮ LIỆU CINEMAS
-- ============================================================

INSERT INTO public.cinemas
(
    id,
    name,
    address,
    city,
    contact_phone,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'MSS Cinema Nguyen Hue',
        '86 Nguyen Hue, Ben Nghe, District 1',
        'Ho Chi Minh City',
        '02838220001',
        10.7732000,
        106.7039000,
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'MSS Cinema Hoan Kiem',
        '25 Trang Tien, Hoan Kiem',
        'Ha Noi',
        '02439360002',
        21.0245000,
        105.8542000,
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'MSS Cinema Da Nang',
        '120 Bach Dang, Hai Chau',
        'Da Nang',
        '02363550003',
        16.0678000,
        108.2208000,
        'INACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 3.7. DỮ LIỆU SEAT_TYPES
-- ============================================================

INSERT INTO public.seat_types
(
    id,
    code,
    name,
    description,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'STANDARD',
        'Standard Seat',
        'Ghế tiêu chuẩn dành cho hầu hết phòng chiếu.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'VIP',
        'VIP Seat',
        'Ghế rộng, vị trí đẹp và có khoảng để chân lớn.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'COUPLE',
        'Couple Seat',
        'Ghế đôi dành cho hai khách, không có tay vịn ở giữa.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 3.8. DỮ LIỆU HALLS
-- ============================================================

INSERT INTO public.halls
(
    id,
    cinema_id,
    name,
    capacity,
    hall_type,
    status,
    created_at,
    updated_at
)
VALUES
    (
        1,
        1,
        'Hall 01',
        20,
        'STANDARD',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        1,
        'VIP 01',
        12,
        'VIP',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        1,
        'IMAX 01',
        16,
        'IMAX',
        'MAINTENANCE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        2,
        'Hall 01',
        20,
        'STANDARD',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        2,
        '4DX 01',
        12,
        'FOUR_DX',
        'ACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        3,
        'Hall 01',
        8,
        'STANDARD',
        'INACTIVE',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 3.9. GHẾ HALL 1
-- A1-A10: STANDARD
-- B1-B10: VIP
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    1,
    CASE
        WHEN generated_seats.row_name = 'A' THEN 1
        ELSE 2
        END,
    generated_seats.row_name,
    generated_seats.seat_number,
    CASE
        WHEN generated_seats.row_name = 'A'
            AND generated_seats.seat_number = 5
            THEN 'BROKEN'

        WHEN generated_seats.row_name = 'B'
            AND generated_seats.seat_number = 10
            THEN 'DISABLED'

        ELSE 'ACTIVE'
        END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    (
        SELECT
            'A'::VARCHAR AS row_name,
                generate_series(1, 10) AS seat_number

        UNION ALL

        SELECT
            'B'::VARCHAR AS row_name,
                generate_series(1, 10) AS seat_number
    ) AS generated_seats;


-- ============================================================
-- 3.10. GHẾ HALL 2
-- C1-C6: VIP
-- D1-D6: COUPLE
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    2,
    CASE
        WHEN generated_seats.row_name = 'C' THEN 2
        ELSE 3
        END,
    generated_seats.row_name,
    generated_seats.seat_number,
    CASE
        WHEN generated_seats.row_name = 'C'
            AND generated_seats.seat_number = 3
            THEN 'BROKEN'
        ELSE 'ACTIVE'
        END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    (
        SELECT
            'C'::VARCHAR AS row_name,
                generate_series(1, 6) AS seat_number

        UNION ALL

        SELECT
            'D'::VARCHAR AS row_name,
                generate_series(1, 6) AS seat_number
    ) AS generated_seats;


-- ============================================================
-- 3.11. GHẾ HALL 3
-- E1-E8: STANDARD
-- F1-F8: VIP
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    3,
    CASE
        WHEN generated_seats.row_name = 'E' THEN 1
        ELSE 2
        END,
    generated_seats.row_name,
    generated_seats.seat_number,
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    (
        SELECT
            'E'::VARCHAR AS row_name,
                generate_series(1, 8) AS seat_number

        UNION ALL

        SELECT
            'F'::VARCHAR AS row_name,
                generate_series(1, 8) AS seat_number
    ) AS generated_seats;


-- ============================================================
-- 3.12. GHẾ HALL 4
-- A1-A10: STANDARD
-- B1-B10: VIP
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    4,
    CASE
        WHEN generated_seats.row_name = 'A' THEN 1
        ELSE 2
        END,
    generated_seats.row_name,
    generated_seats.seat_number,
    CASE
        WHEN generated_seats.row_name = 'B'
            AND generated_seats.seat_number = 8
            THEN 'DISABLED'
        ELSE 'ACTIVE'
        END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    (
        SELECT
            'A'::VARCHAR AS row_name,
                generate_series(1, 10) AS seat_number

        UNION ALL

        SELECT
            'B'::VARCHAR AS row_name,
                generate_series(1, 10) AS seat_number
    ) AS generated_seats;


-- ============================================================
-- 3.13. GHẾ HALL 5
-- G1-G6: STANDARD
-- H1-H6: VIP
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    5,
    CASE
        WHEN generated_seats.row_name = 'G' THEN 1
        ELSE 2
        END,
    generated_seats.row_name,
    generated_seats.seat_number,
    CASE
        WHEN generated_seats.row_name = 'G'
            AND generated_seats.seat_number = 1
            THEN 'BROKEN'
        ELSE 'ACTIVE'
        END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    (
        SELECT
            'G'::VARCHAR AS row_name,
                generate_series(1, 6) AS seat_number

        UNION ALL

        SELECT
            'H'::VARCHAR AS row_name,
                generate_series(1, 6) AS seat_number
    ) AS generated_seats;


-- ============================================================
-- 3.14. GHẾ HALL 6
-- I1-I8: STANDARD, DISABLED
-- ============================================================

INSERT INTO public.seats
(
    hall_id,
    seat_type_id,
    row_name,
    seat_number,
    status,
    created_at,
    updated_at
)
SELECT
    6,
    1,
    'I',
    generate_series(1, 8),
    'DISABLED',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP;


-- ============================================================
-- 3.15. DỮ LIỆU HALL_MAINTENANCE
-- ============================================================

INSERT INTO public.hall_maintenance
(
    hall_id,
    start_time,
    end_time,
    reason,
    status,
    created_at,
    updated_at
)
VALUES
    (
        2,
        CURRENT_TIMESTAMP + INTERVAL '7 days',
        CURRENT_TIMESTAMP + INTERVAL '7 days 4 hours',
        'Bảo trì định kỳ hệ thống âm thanh phòng VIP.',
        'SCHEDULED',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        CURRENT_TIMESTAMP - INTERVAL '1 hour',
        CURRENT_TIMESTAMP + INTERVAL '3 hours',
        'Kiểm tra chuyển động ghế và hiệu ứng phòng 4DX.',
        'IN_PROGRESS',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        CURRENT_TIMESTAMP - INTERVAL '30 days',
        CURRENT_TIMESTAMP - INTERVAL '29 days 20 hours',
        'Thay bóng chiếu và cân chỉnh màn hình IMAX.',
        'COMPLETED',
        CURRENT_TIMESTAMP - INTERVAL '30 days',
        CURRENT_TIMESTAMP - INTERVAL '29 days 20 hours'
    ),
    (
        4,
        CURRENT_TIMESTAMP + INTERVAL '14 days',
        CURRENT_TIMESTAMP + INTERVAL '14 days 2 hours',
        'Lịch vệ sinh sâu phòng chiếu được dời sang tháng sau.',
        'CANCELLED',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );


-- ============================================================
-- 3.16. CẬP NHẬT SEQUENCE CINEMA
-- ============================================================

SELECT setval(
               pg_get_serial_sequence('public.cinemas', 'id'),
               (SELECT MAX(id) FROM public.cinemas),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.seat_types', 'id'),
               (SELECT MAX(id) FROM public.seat_types),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.halls', 'id'),
               (SELECT MAX(id) FROM public.halls),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.seats', 'id'),
               (SELECT MAX(id) FROM public.seats),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.hall_maintenance', 'id'),
               (SELECT MAX(id) FROM public.hall_maintenance),
               TRUE
       );


-- ============================================================
-- PHẦN 4: BOOKING DATABASE
-- ============================================================

-- ============================================================
-- SHOWTIME DATABASE
-- The Showtime Service normally creates this table through Hibernate.
-- Keeping it here makes a fresh PostgreSQL volume usable immediately,
-- regardless of the order in which services are started.
-- ============================================================

\connect showtime_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;

CREATE TABLE public.showtimes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id        BIGINT NOT NULL,
    cinema_id       BIGINT NOT NULL,
    room_id         BIGINT NOT NULL,
    show_date       DATE NOT NULL,
    start_time      TIME WITHOUT TIME ZONE NOT NULL,
    end_time        TIME WITHOUT TIME ZONE NOT NULL,
    price           NUMERIC(19, 2) NOT NULL,
    available_seats INTEGER NOT NULL,
    status          VARCHAR(20) NOT NULL,

    CONSTRAINT chk_showtimes_status
        CHECK (status IN ('AVAILABLE', 'FULL', 'CANCELLED')),
    CONSTRAINT chk_showtimes_available_seats
        CHECK (available_seats >= 0),
    CONSTRAINT chk_showtimes_time_range
        CHECK (end_time > start_time),
    CONSTRAINT uq_showtimes_room_date_start
        UNIQUE (room_id, show_date, start_time)
);

CREATE INDEX idx_showtimes_movie_date
    ON public.showtimes (movie_id, show_date);

CREATE INDEX idx_showtimes_cinema_date
    ON public.showtimes (cinema_id, show_date);

\connect booking_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;


-- ============================================================
-- 4.1. TẠO BẢNG BOOKING_SETTINGS
-- ============================================================

CREATE TABLE public.booking_settings
(
    id            BIGSERIAL PRIMARY KEY,
    setting_key   VARCHAR(100) NOT NULL UNIQUE,
    setting_value VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4.2. TẠO BẢNG SEAT_HOLDS
-- ============================================================

CREATE TABLE public.seat_holds
(
    id          BIGSERIAL PRIMARY KEY,
    hold_token  VARCHAR(100) NOT NULL UNIQUE,
    user_id     BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4.3. TẠO BẢNG SEAT_HOLD_SEATS
-- ============================================================

CREATE TABLE public.seat_hold_seats
(
    id          BIGSERIAL PRIMARY KEY,
    hold_id     BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    seat_code   VARCHAR(20) NOT NULL,
    seat_type   VARCHAR(30),
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_seat_hold_seats_hold
        FOREIGN KEY (hold_id)
            REFERENCES public.seat_holds (id)
            ON DELETE CASCADE,

    -- A seat can appear in several historical holds. Availability is enforced
    -- only for ACTIVE, non-expired holds by Booking Service.
    CONSTRAINT uc_seat_hold_seats_hold_seat
        UNIQUE (hold_id, seat_code)
);


-- ============================================================
-- 4.4. TẠO BẢNG BOOKINGS
-- ============================================================

CREATE TABLE public.bookings
(
    id           BIGSERIAL PRIMARY KEY,
    booking_code VARCHAR(50) NOT NULL UNIQUE,
    user_id      BIGINT NOT NULL,
    customer_email VARCHAR(255),
    customer_name  VARCHAR(255),
    showtime_id  BIGINT NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    status       VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
    hold_token   VARCHAR(100),
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4.5. TẠO BẢNG BOOKING_SEATS
-- ============================================================

CREATE TABLE public.booking_seats
(
    id          BIGSERIAL PRIMARY KEY,
    booking_id  BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    seat_code   VARCHAR(20) NOT NULL,
    seat_type   VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    price       NUMERIC(12,2) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_seats_booking
        FOREIGN KEY (booking_id)
            REFERENCES public.bookings (id)
            ON DELETE CASCADE
);


-- ============================================================
-- 4.6. TẠO BẢNG TICKETS
-- ============================================================

CREATE TABLE public.tickets
(
    id           BIGSERIAL PRIMARY KEY,
    ticket_code  VARCHAR(50) NOT NULL UNIQUE,
    booking_id   BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    showtime_id  BIGINT NOT NULL,
    movie_id     BIGINT NOT NULL,
    movie_title  VARCHAR(255) NOT NULL,
    movie_poster_url VARCHAR(500),
    cinema_id    BIGINT NOT NULL,
    cinema_name  VARCHAR(255) NOT NULL,
    hall_id      BIGINT NOT NULL,
    hall_name    VARCHAR(100) NOT NULL,
    seat_code    VARCHAR(20) NOT NULL,
    seat_type    VARCHAR(20) NOT NULL,
    show_date    DATE NOT NULL,
    start_time TIME(6) WITHOUT TIME ZONE NOT NULL,
    end_time   TIME(6) WITHOUT TIME ZONE NOT NULL,
    price        NUMERIC(12,2) NOT NULL,
    qr_payload   TEXT NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    issued_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tickets_booking
        FOREIGN KEY (booking_id)
            REFERENCES public.bookings (id)
            ON DELETE CASCADE
);


-- ============================================================
-- 4.7. TẠO BẢNG PAYMENTS
-- ============================================================

CREATE TABLE public.payments
(
    id              BIGSERIAL PRIMARY KEY,
    booking_id      BIGINT NOT NULL,
    transaction_ref VARCHAR(100) NOT NULL UNIQUE,
    method          VARCHAR(20) NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    failure_reason  VARCHAR(255),
    vnp_transaction_no VARCHAR(50),
    raw_response    TEXT,
    paid_at         TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id)
            REFERENCES public.bookings (id)
            ON DELETE CASCADE
);


-- ============================================================
-- 4.8. TẠO BẢNG SAGA_TRANSACTIONS
-- ============================================================

CREATE TABLE public.saga_transactions
(
    id             BIGSERIAL PRIMARY KEY,
    saga_id        VARCHAR(100) NOT NULL UNIQUE,
    booking_id     BIGINT NOT NULL,
    status         VARCHAR(30) NOT NULL,
    current_step   VARCHAR(50) NOT NULL,
    failure_reason VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4.9. TẠO BẢNG BOOKING_EVENT_OUTBOX
-- ============================================================

CREATE TABLE public.booking_event_outbox
(
    id             BIGSERIAL PRIMARY KEY,
    event_id       VARCHAR(100) NOT NULL UNIQUE,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    booking_id     BIGINT,
    event_type     VARCHAR(100) NOT NULL,
    topic          VARCHAR(100) NOT NULL,
    payload_json   TEXT NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count    INTEGER NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    published_at   TIMESTAMP WITHOUT TIME ZONE
);


-- ============================================================
-- 4.10. TẠO BẢNG IDEMPOTENCY_RECORDS
-- ============================================================

CREATE TABLE public.idempotency_records
(
    id                BIGSERIAL PRIMARY KEY,
    idempotency_key   VARCHAR(100) NOT NULL UNIQUE,
    request_hash      VARCHAR(100),
    operation_type    VARCHAR(50) NOT NULL,
    status            VARCHAR(20) NOT NULL,
    response_body     TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


-- ============================================================
-- 4.11. INDEX BOOKING
-- ============================================================

CREATE INDEX idx_seat_holds_showtime_status
    ON public.seat_holds (showtime_id, status);

CREATE INDEX idx_seat_holds_expires_at
    ON public.seat_holds (expires_at);

CREATE INDEX idx_bookings_user_status
    ON public.bookings (user_id, status);

CREATE INDEX idx_bookings_showtime
    ON public.bookings (showtime_id);

CREATE INDEX idx_booking_seats_booking
    ON public.booking_seats (booking_id);

CREATE INDEX idx_tickets_booking
    ON public.tickets (booking_id);

CREATE INDEX idx_tickets_user
    ON public.tickets (user_id);

CREATE INDEX idx_payments_booking
    ON public.payments (booking_id);

CREATE INDEX idx_outbox_status_created_at
    ON public.booking_event_outbox (status, created_at);


-- ============================================================
-- 4.12. DỮ LIỆU BOOKING_SETTINGS
-- ============================================================

INSERT INTO public.booking_settings
(
    setting_key,
    setting_value,
    description
)
VALUES
    (
        'seat_hold_ttl_minutes',
        '3',
        'Thời gian giữ ghế tạm thời tính bằng phút'
    ),
    (
        'max_seats_per_hold',
        '8',
        'Số ghế tối đa mỗi lần giữ'
    ),
    (
        'lock_wait_time_seconds',
        '2',
        'Thời gian chờ Redis lock tính bằng giây'
    ),
    (
        'lock_lease_time_seconds',
        '10',
        'Thời gian Redis lock tồn tại tính bằng giây'
    ),
    (
        'default_ticket_price',
        '90000',
        'Giá vé mặc định tính bằng VNĐ'
    ),
    (
        'hold_payment_extension_minutes',
        '30',
        'Thời gian gia hạn giữ ghế khi chuyển sang VNPay'
    );


-- ============================================================
-- 4.13. DỮ LIỆU SEAT_HOLDS
-- ============================================================

/* Historical booking seed data intentionally removed.
INSERT INTO public.seat_holds
(
    id,
    hold_token,
    user_id,
    showtime_id,
    status,
    expires_at,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'HOLD_EXPIRED_001',
        1,
        101,
        'EXPIRED',
        CURRENT_TIMESTAMP - INTERVAL '10 minutes',
        CURRENT_TIMESTAMP - INTERVAL '15 minutes',
        CURRENT_TIMESTAMP - INTERVAL '10 minutes'
    ),
    (
        2,
        'HOLD_ACTIVE_001',
        2,
        101,
        'ACTIVE',
        CURRENT_TIMESTAMP + INTERVAL '4 minutes',
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    );


-- ============================================================
-- 4.14. DỮ LIỆU SEAT_HOLD_SEATS
-- ============================================================

INSERT INTO public.seat_hold_seats
(
    hold_id,
    showtime_id,
    seat_code,
    created_at
)
VALUES
    (
        1,
        101,
        'A1',
        CURRENT_TIMESTAMP - INTERVAL '15 minutes'
    ),
    (
        1,
        101,
        'A2',
        CURRENT_TIMESTAMP - INTERVAL '15 minutes'
    ),
    (
        2,
        101,
        'B1',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    ),
    (
        2,
        101,
        'B2',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    );


-- ============================================================
-- 4.15. DỮ LIỆU BOOKINGS
-- ============================================================

INSERT INTO public.bookings
(
    id,
    booking_code,
    user_id,
    showtime_id,
    total_amount,
    status,
    hold_token,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'BK_CONFIRMED_001',
        1,
        101,
        180000.00,
        'CONFIRMED',
        'HOLD_CONVERTED_001',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        2,
        'BK_PENDING_001',
        2,
        101,
        90000.00,
        'PENDING_PAYMENT',
        'HOLD_ACTIVE_001',
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    ),
    (
        3,
        'BK_CANCELLED_001',
        3,
        102,
        120000.00,
        'CANCELLED',
        'HOLD_CANCELLED_001',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        4,
        'BK_FAILED_001',
        4,
        103,
        150000.00,
        'FAILED',
        'HOLD_FAILED_001',
        CURRENT_TIMESTAMP - INTERVAL '3 hours',
        CURRENT_TIMESTAMP - INTERVAL '3 hours'
    );


-- ============================================================
-- 4.16. DỮ LIỆU BOOKING_SEATS
-- ============================================================

INSERT INTO public.booking_seats
(
    booking_id,
    showtime_id,
    seat_code,
    seat_type,
    price,
    status,
    created_at
)
VALUES
    (
        1,
        101,
        'A1',
        'NORMAL',
        90000.00,
        'CONFIRMED',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        1,
        101,
        'A2',
        'NORMAL',
        90000.00,
        'CONFIRMED',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        2,
        101,
        'B1',
        'VIP',
        90000.00,
        'PENDING',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    ),
    (
        3,
        102,
        'C1',
        'NORMAL',
        120000.00,
        'CANCELLED',
        CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        4,
        103,
        'D1',
        'COUPLE',
        150000.00,
        'CANCELLED',
        CURRENT_TIMESTAMP - INTERVAL '3 hours'
    );


-- ============================================================
-- 4.17. DỮ LIỆU TICKETS
--
-- movie_id 1  = Stellar Horizon
-- cinema_id 1 = MSS Cinema Nguyen Hue
-- hall_id 1   = Hall 01
-- ============================================================

INSERT INTO public.tickets
(
    id,
    ticket_code,
    booking_id,
    user_id,
    showtime_id,
    movie_id,
    movie_title,
    cinema_id,
    cinema_name,
    hall_id,
    hall_name,
    seat_code,
    seat_type,
    show_date,
    start_time,
    end_time,
    price,
    qr_payload,
    status,
    issued_at,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'TK_CONFIRMED_001',
        1,
        1,
        101,
        1,
        'Stellar Horizon',
        1,
        'MSS Cinema Nguyen Hue',
        1,
        'Hall 01',
        'A1',
        'NORMAL',
        CURRENT_DATE,
        '19:00',
        '21:30',
        90000.00,
        'QR:TK_CONFIRMED_001:STELLAR:A1:'
            || TO_CHAR(CURRENT_DATE, 'YYYYMMDD')
            || '1900',
        'ACTIVE',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        2,
        'TK_CONFIRMED_002',
        1,
        1,
        101,
        1,
        'Stellar Horizon',
        1,
        'MSS Cinema Nguyen Hue',
        1,
        'Hall 01',
        'A2',
        'NORMAL',
        CURRENT_DATE,
        '19:00',
        '21:30',
        90000.00,
        'QR:TK_CONFIRMED_002:STELLAR:A2:'
            || TO_CHAR(CURRENT_DATE, 'YYYYMMDD')
            || '1900',
        'ACTIVE',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    );


-- ============================================================
-- 4.18. DỮ LIỆU PAYMENTS
-- ============================================================

INSERT INTO public.payments
(
    id,
    booking_id,
    transaction_ref,
    method,
    amount,
    status,
    failure_reason,
    paid_at,
    created_at,
    updated_at
)
VALUES
    (
        1,
        1,
        'TXN_MOCK_001',
        'MOCK',
        180000.00,
        'PAID',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        2,
        2,
        'TXN_VNPAY_001',
        'VNPAY',
        90000.00,
        'PENDING',
        NULL,
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    ),
    (
        3,
        3,
        'TXN_REFUND_001',
        'MOCK',
        120000.00,
        'PAID',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        4,
        4,
        'TXN_FAILED_001',
        'MOCK',
        150000.00,
        'FAILED',
        'Payment gateway timeout',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '3 hours',
        CURRENT_TIMESTAMP - INTERVAL '3 hours'
    );


-- ============================================================
-- 4.19. DỮ LIỆU SAGA_TRANSACTIONS
-- ============================================================

INSERT INTO public.saga_transactions
(
    id,
    saga_id,
    booking_id,
    status,
    current_step,
    failure_reason,
    created_at,
    updated_at
)
VALUES
    (
        1,
        'SAGA_CONFIRMED_001',
        1,
        'COMPLETED',
        'ISSUE_TICKET',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        2,
        'SAGA_PENDING_001',
        2,
        'STARTED',
        'PAYMENT',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        CURRENT_TIMESTAMP - INTERVAL '1 minute'
    ),
    (
        3,
        'SAGA_CANCELLED_001',
        3,
        'COMPLETED',
        'CANCEL',
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        4,
        'SAGA_FAILED_001',
        4,
        'COMPENSATED',
        'PAYMENT',
        'Payment gateway timeout',
        CURRENT_TIMESTAMP - INTERVAL '3 hours',
        CURRENT_TIMESTAMP - INTERVAL '3 hours'
    );


-- ============================================================
-- 4.20. DỮ LIỆU BOOKING_EVENT_OUTBOX
-- ============================================================

INSERT INTO public.booking_event_outbox
(
    event_id,
    aggregate_type,
    aggregate_id,
    booking_id,
    event_type,
    topic,
    payload_json,
    status,
    retry_count,
    created_at,
    published_at
)
VALUES
    (
        'EVT_BOOKING_CONFIRMED_001',
        'BOOKING',
        'BK_CONFIRMED_001',
        1,
        'BookingConfirmed',
        'booking.confirmed',
        '{"bookingCode":"BK_CONFIRMED_001","userId":1,"showtimeId":101}',
        'PUBLISHED',
        0,
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        'EVT_TICKET_BOOKED_001',
        'TICKET',
        'TK_CONFIRMED_001',
        1,
        'TicketBookedEvent',
        'booking.ticket-booked',
        '{"bookingCode":"BK_CONFIRMED_001","tickets":[{"ticketCode":"TK_CONFIRMED_001","seatCode":"A1"},{"ticketCode":"TK_CONFIRMED_002","seatCode":"A2"}]}',
        'PUBLISHED',
        0,
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP - INTERVAL '2 hours'
    ),
    (
        'EVT_PENDING_001',
        'BOOKING',
        'BK_PENDING_001',
        2,
        'SeatHoldCreated',
        'booking.seat-hold.created',
        '{"holdToken":"HOLD_ACTIVE_001","userId":2,"showtimeId":101,"seatCodes":["B1","B2"]}',
        'PENDING',
        0,
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        NULL
    );


-- ============================================================
-- 4.21. DỮ LIỆU IDEMPOTENCY_RECORDS
-- ============================================================

INSERT INTO public.idempotency_records
(
    idempotency_key,
    request_hash,
    operation_type,
    status,
    response_body,
    created_at,
    expires_at
)
VALUES
    (
        'IDEM_HOLD_001',
        'hash_hold_001',
        'HOLD',
        'SUCCEEDED',
        '{"holdToken":"HOLD_ACTIVE_001"}',
        CURRENT_TIMESTAMP - INTERVAL '1 minute',
        CURRENT_TIMESTAMP + INTERVAL '4 minutes'
    ),
    (
        'IDEM_CONFIRM_001',
        'hash_confirm_001',
        'CONFIRM',
        'SUCCEEDED',
        '{"bookingCode":"BK_CONFIRMED_001","status":"CONFIRMED"}',
        CURRENT_TIMESTAMP - INTERVAL '2 hours',
        CURRENT_TIMESTAMP + INTERVAL '1 day'
    ),
    (
        'IDEM_CANCEL_001',
        'hash_cancel_001',
        'CANCEL',
        'SUCCEEDED',
        '{"bookingCode":"BK_CANCELLED_001","status":"CANCELLED"}',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP + INTERVAL '6 days'
    );


-- ============================================================
-- 4.22. CẬP NHẬT SEQUENCE BOOKING
-- ============================================================

*/
SELECT setval(
               pg_get_serial_sequence('public.booking_settings', 'id'),
               (SELECT MAX(id) FROM public.booking_settings),
               TRUE
       );

SELECT setval(
               pg_get_serial_sequence('public.seat_holds', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.seat_hold_seats', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.bookings', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.booking_seats', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.tickets', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.payments', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.saga_transactions', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.booking_event_outbox', 'id'),
               1,
               FALSE
       );

SELECT setval(
               pg_get_serial_sequence('public.idempotency_records', 'id'),
               1,
               FALSE
       );


-- ============================================================
-- PHẦN 5: KIỂM TRA KẾT QUẢ MOVIE
-- ============================================================

\connect movie_db

SELECT
    'actors' AS table_name,
    COUNT(*) AS row_count
FROM public.actors

UNION ALL

SELECT
    'directors',
    COUNT(*)
FROM public.directors

UNION ALL

SELECT
    'genres',
    COUNT(*)
FROM public.genres

UNION ALL

SELECT
    'movies',
    COUNT(*)
FROM public.movies

UNION ALL

SELECT
    'movie_actors',
    COUNT(*)
FROM public.movie_actors

UNION ALL

SELECT
    'movie_directors',
    COUNT(*)
FROM public.movie_directors

UNION ALL

SELECT
    'movie_genres',
    COUNT(*)
FROM public.movie_genres

ORDER BY table_name;


-- ============================================================
-- PHẦN 6: KIỂM TRA KẾT QUẢ CINEMA
-- ============================================================

\connect cinema_db

SELECT
    'cinemas' AS table_name,
    COUNT(*) AS row_count
FROM public.cinemas

UNION ALL

SELECT
    'halls',
    COUNT(*)
FROM public.halls

UNION ALL

SELECT
    'seat_types',
    COUNT(*)
FROM public.seat_types

UNION ALL

SELECT
    'seats',
    COUNT(*)
FROM public.seats

UNION ALL

SELECT
    'hall_maintenance',
    COUNT(*)
FROM public.hall_maintenance

ORDER BY table_name;


SELECT
    c.name AS cinema_name,
    h.name AS hall_name,
    h.capacity,
    COUNT(s.id) AS actual_seat_count
FROM public.halls h
         JOIN public.cinemas c
              ON c.id = h.cinema_id
         LEFT JOIN public.seats s
                   ON s.hall_id = h.id
GROUP BY
    c.name,
    h.name,
    h.capacity
ORDER BY
    c.name,
    h.name;


-- ============================================================
-- PHẦN 7: KIỂM TRA KẾT QUẢ BOOKING
-- ============================================================

\connect booking_db

SELECT
    'booking_settings' AS table_name,
    COUNT(*) AS row_count
FROM public.booking_settings

UNION ALL

SELECT
    'seat_holds',
    COUNT(*)
FROM public.seat_holds

UNION ALL

SELECT
    'seat_hold_seats',
    COUNT(*)
FROM public.seat_hold_seats

UNION ALL

SELECT
    'bookings',
    COUNT(*)
FROM public.bookings

UNION ALL

SELECT
    'booking_seats',
    COUNT(*)
FROM public.booking_seats

UNION ALL

SELECT
    'tickets',
    COUNT(*)
FROM public.tickets

UNION ALL

SELECT
    'payments',
    COUNT(*)
FROM public.payments

UNION ALL

SELECT
    'saga_transactions',
    COUNT(*)
FROM public.saga_transactions

UNION ALL

SELECT
    'booking_event_outbox',
    COUNT(*)
FROM public.booking_event_outbox

UNION ALL

SELECT
    'idempotency_records',
    COUNT(*)
FROM public.idempotency_records

ORDER BY table_name;



-- ============================================================
-- PHẦN 8: NOTIFICATION DATABASE
-- ============================================================

\connect notification_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET search_path TO public;


-- ============================================================
-- 8.1. TẠO BẢNG NOTIFICATION_LOGS
-- ============================================================

CREATE TABLE public.notification_logs
(
    id              UUID NOT NULL,
    recipient_email VARCHAR(320) NOT NULL,
    subject         VARCHAR(500) NOT NULL,
    message         TEXT NOT NULL,
    channel         VARCHAR(30) NOT NULL,
    type            VARCHAR(50) NOT NULL,
    status          VARCHAR(30) NOT NULL,
    error_message   TEXT,
    source_event_id VARCHAR(255),
    source_topic    VARCHAR(255),
    retry_count     INTEGER NOT NULL DEFAULT 0,
    max_retries     INTEGER NOT NULL DEFAULT 3,
    next_retry_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    scheduled_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    sent_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT notification_logs_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_notification_logs_source_event_topic
        UNIQUE (source_event_id, source_topic),

    CONSTRAINT notification_logs_channel_check
        CHECK (channel IN ('EMAIL', 'SMS', 'PUSH')),

    CONSTRAINT notification_logs_type_check
        CHECK (type IN (
                        'BOOKING_CONFIRMATION',
                        'BOOKING_CANCELLED',
                        'SEAT_HOLD_CREATED',
                        'SEAT_HOLD_EXPIRED',
                        'PAYMENT_SUCCESS',
                        'PAYMENT_FAILED',
                        'PAYMENT_REFUND_REQUIRED',
                        'SHOWTIME_REMINDER',
                        'TICKET_BOOKED',
                        'TICKET_CANCELLED',
                        'SYSTEM_ALERT'
            )),

    CONSTRAINT notification_logs_status_check
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'RETRYING')),

    CONSTRAINT notification_logs_retry_count_check
        CHECK (retry_count >= 0),

    CONSTRAINT notification_logs_max_retries_check
        CHECK (max_retries >= 0)
);

CREATE INDEX idx_notification_logs_status_created_at
    ON public.notification_logs (status, created_at DESC);

CREATE INDEX idx_notification_logs_recipient_email
    ON public.notification_logs (recipient_email);

CREATE INDEX idx_notification_logs_due_retry
    ON public.notification_logs (status, next_retry_at)
    WHERE status = 'RETRYING';

CREATE INDEX idx_notification_logs_due_scheduled
    ON public.notification_logs (status, scheduled_at)
    WHERE status = 'PENDING';


-- ============================================================
-- 8.2. TẠO BẢNG NOTIFICATION_TEMPLATES
-- ============================================================

CREATE TABLE public.notification_templates
(
    id      UUID NOT NULL,
    code    VARCHAR(100) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body    TEXT NOT NULL,

    CONSTRAINT notification_templates_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_notification_templates_code
        UNIQUE (code)
);


-- ============================================================
-- 8.3. DỮ LIỆU MẪU NOTIFICATION_TEMPLATES
-- ============================================================

INSERT INTO public.notification_templates (id, code, subject, body)
VALUES
    (
        '00000000-0000-0000-0000-000000000101',
        'BOOKING_CONFIRMATION',
        'Xác nhận đặt vé thành công - {{bookingCode}}',
        'Xin chào {{customerName}},

Bạn đã đặt vé thành công.
Mã booking: {{bookingCode}}
Phim: {{movieTitle}}
Suất chiếu: {{showtimeLabel}}
Tổng tiền: {{totalAmount}}

Mã QR vé đã được đính kèm trong email. Vui lòng đưa mã QR cho nhân viên rạp khi check-in.'
    ),
    (
        '00000000-0000-0000-0000-000000000102',
        'SHOWTIME_REMINDER',
        'Nhắc lịch xem phim - {{bookingCode}}',
        'Xin chào {{customerName}},

Suất chiếu của bạn sắp bắt đầu.
Mã booking: {{bookingCode}}
Phim: {{movieTitle}}
Thời gian: {{showtimeLabel}}

Vui lòng đến rạp sớm để check-in và ổn định chỗ ngồi.'
    ),
    (
        '00000000-0000-0000-0000-000000000103',
        'TICKET_BOOKED',
        'Vé xem phim đã sẵn sàng - {{bookingCode}}',
        'Xin chào {{customerName}},

Vé của booking {{bookingCode}} đã được phát hành.
{{ticketSummary}}
Mã QR vé đã được đính kèm trong email.'
    ),
    (
        '00000000-0000-0000-0000-000000000104',
        'BOOKING_CANCELLED',
        'Thông báo hủy vé - {{bookingCode}}',
        'Xin chào {{customerName}},

Booking {{bookingCode}} của bạn đã được hủy.
Lý do: {{reason}}

Nếu booking đã thanh toán, hệ thống sẽ xử lý hoàn tiền theo chính sách của rạp.'
    ),
    (
        '00000000-0000-0000-0000-000000000105',
        'PAYMENT_SUCCESS',
        'Thanh toán thành công - {{paymentCode}}',
        'Xin chào {{customerName}},

Thanh toán {{paymentCode}} đã hoàn tất thành công.
Booking: {{bookingCode}}
Số tiền: {{amount}}

Bạn có thể xem lại giao dịch trong mục Thanh toán của tài khoản.'
    ),
    (
        '00000000-0000-0000-0000-000000000106',
        'PAYMENT_FAILED',
        'Thanh toán thất bại - {{paymentCode}}',
        'Xin chào {{customerName}},

Thanh toán {{paymentCode}} chưa thành công.
Booking: {{bookingCode}}
Số tiền: {{amount}}
Lý do: {{reason}}

Vui lòng thử lại hoặc liên hệ rạp nếu cần hỗ trợ.'
    ),
    (
        '00000000-0000-0000-0000-000000000107',
        'PAYMENT_REFUND_REQUIRED',
        'Thông báo hoàn tiền - {{bookingCode}}',
        'Xin chào {{customerName}},

Giao dịch {{paymentCode}} cho booking {{bookingCode}} đang được xử lý hoàn tiền.
Số tiền: {{amount}}
Lý do: {{reason}}.'
    ),
    (
        '00000000-0000-0000-0000-000000000108',
        'SEAT_HOLD_CREATED',
        'Bạn đang giữ ghế - {{holdToken}}',
        'Xin chào {{customerName}},

Bạn đang giữ ghế với mã giữ chỗ {{holdToken}}.
Thời gian hết hạn: {{expiresAt}}.
Vui lòng hoàn tất thanh toán trước khi hết hạn để xác nhận vé.'
    ),
    (
        '00000000-0000-0000-0000-000000000109',
        'SEAT_HOLD_EXPIRED',
        'Mã giữ ghế đã hết hạn - {{holdToken}}',
        'Xin chào {{customerName}},

Mã giữ chỗ {{holdToken}} đã hết hạn. Các ghế trong lượt giữ này đã được mở lại cho người dùng khác.'
    )
    ON CONFLICT (code) DO NOTHING;


-- ============================================================
-- PHẦN 9: KIỂM TRA KẾT QUẢ NOTIFICATION
-- ============================================================

SELECT
    'notification_logs' AS table_name,
    COUNT(*) AS row_count
FROM public.notification_logs

UNION ALL

SELECT
    'notification_templates',
    COUNT(*)
FROM public.notification_templates

ORDER BY table_name;


-- ============================================================
-- PHẦN 10: KẾT THÚC
-- ============================================================

\connect postgres

SELECT
    'Initialization completed successfully: Movie, Cinema, Booking and Notification schemas with demo data were created.'
        AS initialization_result;
